name: narratrivia
description: "App trivia narrativa multilingua con domande su anime, manga, videogiochi, serie TV, film e libri"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  audioplayers: ^6.5.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter

  # Firebase - versioni stabili
  firebase_core: ^4.0.0
  firebase_analytics: ^12.0.0
  #firebase_firestore: ^4.14.0
  firebase_auth: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/backgrounds/arcs/
    - assets/images/backgrounds/rooms/
    - assets/images/logos/
    - assets/images/icons/
    - assets/sounds/
    - assets/sounds/mediums/
    - assets/sounds/sfx/
    - assets/sounds/sfx/ui/

  fonts:
    - family: BitcountGrid
      fonts:
        - asset: assets/fonts/BitcountGrid-DoubleRegular.ttf
    - family: BungeeSpice
      fonts:
        - asset: assets/fonts/BungeeSpice-Regular.ttf
    - family: BungeeTint
      fonts:
        - asset: assets/fonts/BungeeTint-Regular.ttf
    - family: ManufacturingConsent
      fonts:
        - asset: assets/fonts/ManufacturingConsent-regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/RobotoSerif20pt-Italic.ttf
          style: italic
          weight: 200